# Generated by Django 5.1.2 on 2025-03-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_moduleprogress_score_learningpathprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpathprogress',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.learningpath'),
        ),
    ]
