# Generated by Django 5.1.2 on 2025-03-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_learningpathprogress_learning_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='topic',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='learningpath',
            constraint=models.UniqueConstraint(fields=('course', 'path_name'), name='unique_course_path'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('learning_path', 'module_name'), name='unique_path_module'),
        ),
    ]
